# ベースイメージをDebianベースのPythonイメージに変更
FROM public.ecr.aws/docker/library/python:3.12

WORKDIR /app

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app
ENV PYTHONPATH=/app/app

RUN chmod +x /app/scripts/start-uvicorn.sh

CMD ["/app/scripts/start-uvicorn.sh"]
